services:
  cloudcord:
    image: cloudcord
    container_name: "cloudcord"
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: CloudCord/Dockerfile
    volumes:
      - /var/docker-data/cloudcord/keys:/keys
